### ISSUE TITLE
Standardize floating point type

### ISSUE THREAD

**Issue by ghost** [Pitt-RAS/motion-control#13]
Idea: Let's make a `typedef` for a floating point type, so that our type might be changed globally between `float`, `double`, or (though unlikely) another type that can stand in for those.

Then a user of the library might potentially be able to specify what floating point type they want the library to use.

**Comment by 4ndr3w** [comment]
I was thinking something like this too.

In addition to this, what do you think about having a specific type just for the values used in the control process? Along the lines of what you were working on in the generic types branch, but let the user typedef their own. Obviously they would have to design their controllers with this type in mind, but it would allow them to run with our structure. 

For example:
I set `motion_math_t` int_fast32_t

- I build my own motor object to expect this scaled from max int32 to min int32
- I build my controllers expecting integer values

Having a separate type for these operations would allow an advanced user to use integer math for control, but keep things like time in a more generic floating point type

Just a thought, I agree we should create a standardized float regardless

**Comment by ghost** [comment]
That's a good idea. In other words, somebody could implement integer math internally in a `Controller`, and everybody outside is none the wiser. I wonder if it's not too messy to make that a template parameter for `System`, `Controller`, and `Motor`.

We could also potentially make a bunch of categories of types like time, position/velocity/accel, motor/controller output, encoder count... I'm not sure how far we would want to go and at what point it would become useless because of different types being involved in the same operations.

At any rate, I agree it's a good idea to at the least have one generic floating point type and another "math" type that can be any numeric type.

We should choose their names carefully. For example, `motion_math_t` could easily become a bad name if we need two different types for "mathy" operations.
